import {Poppins} from "next/font/google"
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100","300", "400", "600", "700"],
    variable: "--font-poppins",
});

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={`${poppins.variable} antialiased`}>
        {children}
        </body>
        </html>
    );
}
